---
title: "enesmith"
author: "Elisabeth Nesmith"
date: "5/4/2021"
output: html_document
---

```{r}
library(tidyverse)
library(plotly)
```

```{r}
#barplot of races of officers
mos_race_plot <- allegations_2019 %>% 
  group_by(mos_ethnicity) %>% 
  count() %>% 
  mutate(percent = round(n/1642*100, digits = 2)) %>% 
  plot_ly(x = ~mos_ethnicity,
          y = ~n,
          type = 'bar',
          text = ~percent,
          textposition = 'auto') %>% 
  layout(title = "Racial Breakdown of Officers in 2019 Allegations",
         xaxis = list(title = 'Race of Officers'),
         yaxis = list(title = 'Number of Complaints'))

mos_race_plot

#need to add color, figure out how to add percent sign to label on bars, figure out interactive element?
#maybe have option to look at overall demographics and individual precincts?
#or toggle between gender, age, and race
```

```{r}
#barplot of races of complainants
comp_race_plot <- allegations_2019 %>% 
  group_by(complainant_ethnicity) %>% 
  count() %>% 
  mutate(percent = round(n/1642*100, digits = 2)) %>% 
  plot_ly(x = ~complainant_ethnicity,
          y = ~n,
          type = 'bar',
          text = ~percent,
          textposition = 'auto') %>% 
  layout(title = "Racial Breakdown of Complainants in 2019 Allegations",
         xaxis = list(title = 'Race of Complainants'),
         yaxis = list(title = 'Number of Complaints'))

comp_race_plot
```

```{r}
#gender of officers
mos_gender_plot <- allegations_2019 %>% 
  group_by(mos_gender) %>% 
  count() %>% 
  mutate(percent = round(n/1642*100, digits = 2)) %>% 
  plot_ly(x = ~mos_gender,
          y = ~n,
          type = 'bar',
          text = ~percent,
          textposition = 'auto') %>% 
  layout(title = "Gender Breakdown of Officers in 2019 Allegations",
         xaxis = list(title = 'Gender of Officers'),
         yaxis = list(title = 'Number of Complaints'))

mos_gender_plot
```

```{r}
#gender of officers
comp_gender_plot <- allegations_2019 %>% 
  group_by(complainant_gender) %>% 
  count() %>% 
  mutate(percent = round(n/1642*100, digits = 2)) %>% 
  plot_ly(x = ~complainant_gender,
          y = ~n,
          type = 'bar',
          text = ~percent,
          textposition = 'auto') %>% 
  layout(title = "Gender Breakdown of Complainants in 2019 Allegations",
         xaxis = list(title = 'Gender of Complainants'),
         yaxis = list(title = 'Number of Complaints'))

comp_gender_plot
```

```{r}
race_plot <- allegations_2019 %>% 
  plot_ly(x = ~mos_ethnicity,
          y = ~complainant_ethnicity,
          type = 'bar',
          color = ~complainant_ethnicity)

race_plot

#make interactive by choosing race of complainant or race of officer
```

```{r}

```

