---
title: "enesmith"
author: "Elisabeth Nesmith"
date: "5/4/2021"
output: html_document
---

```{r}
library(tidyverse)
library(plotly)
library(here)
library(RColorBrewer)
allegations <- read_csv(here("data", "allegations.csv")) 
allegations_2019 <- allegations %>%  filter(year_received == 2019)
allegations_2016 <- allegations %>%  filter(year_received == 2016)
allegations_2018 <- allegations %>%  filter(year_received == 2018)
```

```{r}
#replace NAs
allegations <- allegations %>% 
  replace_na(list(complainant_ethnicity = 'Unknown', complainant_gender = 'NA', complainant_age_incident = 'NA'))

allegations_2016 <- allegations_2016 %>% 
  replace_na(list(complainant_ethnicity = 'Unknown', complainant_gender = 'NA', complainant_age_incident = 'NA')) 

allegations_2018 <- allegations_2018 %>% 
  replace_na(list(complainant_ethnicity = 'Unknown', complainant_gender = 'NA', complainant_age_incident = 'NA')) 
```




```{r}
#barplot of races of officers 2016
mos_race_2016 <- allegations_2016 %>%
  mutate(name = paste(first_name, last_name)) %>% 
  distinct(name, .keep_all = TRUE) %>% 
  group_by(mos_ethnicity) %>% 
  count() %>% 
  mutate(percent = paste(round(n/744*100, digits = 2),'%', sep = "")) %>% 
  plot_ly(x = ~mos_ethnicity,
          y = ~n,
          type = 'bar',
          text = ~percent,
          textposition = 'auto') %>% 
  layout(title = "Racial Percentages of the 744 Officers in 2016 Allegations",
         xaxis = list(title = 'Race of Officers'),
         yaxis = list(title = 'Number of Complaints'))

mos_race_2016

#need to add color, figure out how to add percent sign to label on bars, figure out interactive element?
#maybe have option to look at overall demographics and individual precincts?
#or toggle between gender, age, and race
```
```{r}
allegations_officers <- allegations %>% 
  mutate(name = paste(first_name, last_name)) %>% 
  distinct(name, .keep_all = TRUE)

mos_race <- allegations_officers %>% 
  group_by(mos_ethnicity) %>% 
  count() %>% 
  mutate(percent = paste(round(n/nrow(allegations_officers)*100, digits = 2),'%', sep = "")) %>% 
  plot_ly(x = ~mos_ethnicity,
          y = ~n,
          type = 'bar',
          text = ~percent,
          textposition = 'auto') %>% 
  layout(title = "Racial Percentages of the Officers in all Allegations",
         xaxis = list(title = 'Race of Officers'),
         yaxis = list(title = 'Number of Complaints'))
mos_race
```


```{r}
#barplot of races of officers 2018
mos_race_2018 <- allegations_2018 %>%
  mutate(name = paste(first_name, last_name)) %>% 
  distinct(name, .keep_all = TRUE) %>% 
  group_by(mos_ethnicity) %>% 
  count() %>% 
  mutate(percent = paste(round(n/726*100, digits = 2),'%', sep = "")) %>% 
  plot_ly(x = ~mos_ethnicity,
          y = ~n,
          type = 'bar',
          text = ~percent,
          textposition = 'auto') %>% 
  layout(title = "Racial Percentages of the 726 Officers in 2018 Allegations",
         xaxis = list(title = 'Race of Officers'),
         yaxis = list(title = 'Number of Complaints'))

mos_race_2018

#need to add color, figure out how to add percent sign to label on bars, figure out interactive element?
#maybe have option to look at overall demographics and individual precincts?
#or toggle between gender, age, and race
```


```{r}
#barplot of races of complainants in 2016
comp_race_2016 <- allegations_2016 %>%
  group_by(complainant_ethnicity) %>% 
  count() %>% 
  mutate(percent = paste(round(n/2345*100, digits = 2),'%', sep = "")) %>% 
  plot_ly(x = ~complainant_ethnicity,
          y = ~n,
          type = 'bar',
          text = ~percent,
          textposition = 'auto') %>% 
  layout(title = "Racial Percentages of 2345 Complainants in 2016 Allegations",
         xaxis = list(title = 'Race of Complainants'),
         yaxis = list(title = 'Number of Complaints'))

comp_race_2016
```

```{r}
#barplot of races of complainants in 2018
comp_race_2018 <- allegations_2018 %>%
  group_by(complainant_ethnicity) %>% 
  count() %>% 
  mutate(percent = paste(round(n/2281*100, digits = 2),'%', sep = "")) %>% 
  plot_ly(x = ~complainant_ethnicity,
          y = ~n,
          type = 'bar',
          text = ~percent,
          textposition = 'auto') %>% 
  layout(title = "Racial Percentages of 2281 Complainants in 2018 Allegations",
         xaxis = list(title = 'Race of Complainants'),
         yaxis = list(title = 'Number of Complaints'))

comp_race_2018
```

```{r}
#gender of officers 2016
mos_gender_2016 <- allegations_2016 %>%
  mutate(name = paste(first_name, last_name)) %>% 
  distinct(name, .keep_all = TRUE) %>% 
  group_by(mos_gender) %>% 
  count() %>%
  mutate(percent = paste(round(n/744*100, digits = 2), '%', sep = "")) %>% 
  plot_ly(x = ~mos_gender,
          y = ~n,
          type = 'bar',
          text = ~percent,
          textposition = 'auto') %>% 
  layout(title = "Gender Percentages of 744 Officers in 2016 Allegations",
         xaxis = list(title = 'Gender of Officers'),
         yaxis = list(title = 'Number of Complaints'))

mos_gender_2016
```

```{r}
#gender of officers 2018
mos_gender_2018 <- allegations_2018 %>%
  mutate(name = paste(first_name, last_name)) %>% 
  distinct(name, .keep_all = TRUE) %>% 
  group_by(mos_gender) %>% 
  count() %>%
  mutate(percent = paste(round(n/726*100, digits = 2), '%', sep = "")) %>% 
  plot_ly(x = ~mos_gender,
          y = ~n,
          type = 'bar',
          text = ~percent,
          textposition = 'auto') %>% 
  layout(title = "Gender Percentages of 726 Officers in 2018 Allegations",
         xaxis = list(title = 'Gender of Officers'),
         yaxis = list(title = 'Number of Complaints'))

mos_gender_2018
```

```{r}
#gender of complainants 2016
comp_gender_2016 <- allegations_2016 %>% 
  group_by(complainant_gender) %>% 
  count() %>% 
  mutate(percent = paste(round(n/2345*100, digits = 2), '%', sep = "")) %>% 
  plot_ly(x = ~complainant_gender,
          y = ~n,
          type = 'bar',
          text = ~percent,
          textposition = 'auto') %>% 
  layout(title = "Gender Breakdown of Complainants in 2016 Allegations",
         xaxis = list(title = 'Gender of Complainants'),
         yaxis = list(title = 'Number of Complaints'))

comp_gender_2016
```

```{r}
#gender of complainants 2018
comp_gender_2018 <- allegations_2018 %>% 
  group_by(complainant_gender) %>% 
  count() %>% 
  mutate(percent = paste(round(n/2281*100, digits = 2), '%', sep = "")) %>% 
  plot_ly(x = ~complainant_gender,
          y = ~n,
          type = 'bar',
          text = ~percent,
          textposition = 'auto') %>% 
  layout(title = "Gender Breakdown of Complainants in 2016 Allegations",
         xaxis = list(title = 'Gender of Complainants'),
         yaxis = list(title = 'Number of Complaints'))

comp_gender_2018
```

```{r}
race_plot1 <- allegations_2019 %>%
  group_by(mos_ethnicity, complainant_ethnicity) %>% 
  count() %>% 
  mutate(combo = paste(mos_ethnicity,complainant_ethnicity)) %>% 
  plot_ly(x = ~combo,
          y = ~n,
          type = 'bar') %>% 
  layout(title = "Race Combos of Officers and Complainants",
         xaxis = list(title = "Race (Officer Complainant)"),
         yaxis = list(title = "Number of Complaints"))

race_plot1

#make interactive by choosing race of complainant or race of officer
```

```{r}
raceplot2 <- allegations_2019 %>%
  plot_ly(x = ~mos_ethnicity,
          y = ~complainant_ethnicity,
          color = ~complainant_ethnicity,
          type = 'bar') %>% 
  layout(title = "Race Combos of Officers and Complainants",
         xaxis = list(title = "Race of Officer"))

raceplot2
```

```{r}
race_plot_2016 <- allegations_2016 %>%
  group_by(mos_ethnicity, complainant_ethnicity) %>% 
  count() %>% 
  plot_ly(x = ~mos_ethnicity,
          y = ~n,
          type = 'bar',
          text = ~complainant_ethnicity,
          hovertemplate = 'Complainant Race: %{text}<br>Officer Race: %{x}<br>%{y}',
          color = ~complainant_ethnicity,
          colors = brewer.pal(8, "Paired")
          ) %>% 
  layout(title = "Distribution of Complainant Race by Officer Race in 2016",
         xaxis = list(title = "Race of Officer"),
         yaxis = list(title = "Number of Complaints"),
         legend = list(title = "Race of Complainant"))

race_plot_2016
```

```{r}
race_plot_2018 <- allegations_2018 %>%
  group_by(mos_ethnicity, complainant_ethnicity) %>% 
  count() %>% 
  plot_ly(x = ~mos_ethnicity,
          y = ~n,
          type = 'bar',
          text = ~complainant_ethnicity,
          hovertemplate = 'Complainant Race: %{text}<br>Officer Race: %{x}<br>%{y}',
          color = ~complainant_ethnicity,
          colors = brewer.pal(8, "Paired")
          ) %>% 
  layout(title = "Distribution of Complainant Race by Officer Race in 2018 Allegations",
         xaxis = list(title = "Race of Officer"),
         yaxis = list(title = "Number of Complaints"))

race_plot_2018
```

```{r}
#race of officers in complaints filed by Black complainants
allegations_2019 %>%
  filter(complainant_ethnicity == 'Black') %>% 
  group_by(mos_ethnicity) %>% 
  count() %>% 
  mutate(percent = round(n/733*100, digits = 2)) %>%
  plot_ly(x = ~mos_ethnicity,
          y = ~n,
          color = ~mos_ethnicity,
          text = ~percent,
          type = 'bar')
```


